name: Deploy Node.js App to Docker Hub

on:
  push:
    branches:
      - main  # Triggers deployment when code is pushed to 'main' branch
  workflow_dispatch:  # Allows manual triggering of the workflow from GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest  # The job runs on the latest Ubuntu environment
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensures full history is fetched (useful for versioning)

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18  # Use the Node.js version your project requires

    - name: Install Dependencies
      run: npm install  # Installs project dependencies from package.json

   

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Metadata for Docker Image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: khushaldhale/node-app-1  # Replace with your Docker Hub repo

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .  # Uses the current directory for building the image
        file: ./Dockerfile  # Specifies the Dockerfile location
        push: true  # Enables pushing the image to Docker Hub
        tags: |
          your-dockerhub-username/node-app:latest
          your-dockerhub-username/node-app:${{ github.sha }}  # Uses commit SHA as a tag for versioning
        labels: ${{ steps.meta.outputs.labels }}  # Adds metadata to the image
